#!/bin/sh
echo "Running Checkstyle..."

mvn checkstyle:check
CHECKSTYLE_STATUS=$?

if [ $CHECKSTYLE_STATUS -ne 0 ]; then
    echo "❌ Checkstyle failed! Fix your errors before committing buddy!"
    exit 1 
fi

echo "✅ Linter checks passed! Proceeding with your commit..."
exit 0
