jwt:
  publicKey: ${PUBLIC_KEY}
  privateKey: ${PRIVATE_KEY}
  audience: "localhost:3000"
cloudflare:
  api:
    accountID: ${CLOUDFLARE_ACCOUNTID}
    key: ${CLOUDFLARE_KEY}
server:
  port: 5454
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_USER_PASSWORD}
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: 61613
    requested-heartbeat: 580
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  environment:
    ALLOWED_ORIGINS:
      - http://localhost:3000
      - http://localhost:4173