jwt:
  public:
    key: classpath:public.pem
  private:
    key: classpath:private.pem
  audience: "localhost:3000"
cloudflare:
  api:
    accountID: ''
    key: ''
server:
  port: 5454
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: FERODO2001
    url: jdbc:mysql://localhost:3306/teamsphere_db
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    password: guest
    port: 61613
    requested-heartbeat: 580
    username: guest
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application.name: TeamSphere


app:
  environment:
    ALLOWED_ORIGINS:
      - http://localhost:3000
      - http://localhost:4173

google:
  client-id:
  client-secret:


